export {
    getFriendsData, 
    postLoginData,
    postFriendData,
    FETCH_FRIENDS_DATA_START,
    FETCH_FRIENDS_DATA_SUCCESS,
    FETCH_FRIENDS_DATA_FAILURE,
    POST_LOGIN_DATA_START,
    POST_LOGIN_DATA_SUCCESS,
    POST_LOGIN_DATA_FAILURE,
    POST_FRIEND_DATA_START,
    POST_FRIEND_DATA_SUCCESS,
    POST_FRIEND_DATA_FAILURE
} from '../actions/loginActions.js';

